import React, { useEffect } from "react";
import audit from '../../../Website Image/Audit.jpeg'
import compliance from '../../../Website Image/bg-compliance2.jpg';
import permit from '../../../Website Image/Permit.jpg';
import knowledgebase from '../../../Website Image/Knowledge base-1.jpg';
import purchase from '../../../Website Image/purchase.jpg';
import reporting from '../../../Website Image/Reporting-1.jpg';

const KnowMorePage2 = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);
  return (
    <div className="bg-gradient-to-r from-pink-700 to-pink-600 text-black p-8">
      {/* First Section */}
      <h1 className="text-3xl font-bold text-red-500 mb-2">Employee Productivity & Efficiency </h1>
<p className="text-xl  mb-2 text-justify font-serif text-gray-800 leading-relaxed">Vibe Connect tools is designed to enhance employee productivity, streamline collaboration, and support professional development within organizations. Employee productivity refers to the output generated by an employee within a specific time frame, while efficiency measures how well resources (including time and effort) are utilized to achieve that output. Enhancing both productivity and efficiency is crucial for organizations to improve performance and competitiveness. Key Factors Influencing Productivity and Efficiency:
</p>
<ul className="list-[disc] list-inside"><li className="text-xl  mb-2 text-justify font-serif text-gray-800 leading-relaxed">Work Environment </li>
<li className="text-xl  mb-2 text-justify font-serif text-gray-800 leading-relaxed">Technology</li>
<li className="text-xl  mb-2 text-justify font-serif text-gray-800 leading-relaxed">Work-Life Balance</li>
<li className="text-xl  mb-2 text-justify font-serif text-gray-800 leading-relaxed">Clear Goals and Feedback</li></ul>
	
	
	
  
<p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed">
Investing in strategies that enhance employee productivity and efficiency not only benefits the workforce but also drives overall organizational success. By creating a supportive environment and providing the necessary resources, companies can optimize performance and achieve sustainable growth.
  </p>
  <div className="flex flex-col gap-8 lg:flex-row justify-between items-center mb-12">
        {/* Content */}
        <div className="lg:w-1/2 mb-8 lg:mb-0">
        <h3 className="text-3xl font-bold  mb-2">				Project & Task Management</h3>

        <p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed">
     <span className="font-bold ">	Project & Task Planning :</span>   Provides tools for planning projects, managing sub-task dependencies, and tracking progress using Kanban or list views, with milestones. Offers task assignment, tracking, and management of deadlines with reminders for timely completion.  </p>
<p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed">	Integration with Tools like WhatsApp for assigning and reminder of pending task.</p>
        </div>
        {/* Image */}
        <div className="lg:w-1/2 flex justify-center">
          <img
            src={compliance}
            alt="AI Automation"
            className="rounded-lg shadow-lg"
          />
        </div>
      </div>
      <div className="flex flex-col gap-8 lg:flex-row-reverse justify-between items-center mb-12">
        {/* Content */}
        <div className="lg:w-1/2 mb-8 lg:mb-0">
        <h3 className="text-3xl font-bold  mb-2">			Communication & Collaboration</h3>

        <p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed">
     <span className="font-bold ">Communication Tools: </span>   Includes instant broadcasts, events, Notices, video conferencing (Zoom, Teams), and email integration, Forums etc for seamless communication. </p>
<p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed"><span className="font-bold ">		Collaboration Tools:  </span>Facilitates document sharing, team collaboration spaces, and internal chats.</p>
<p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed"><span className="font-bold ">	Calendar Integration:  </span>Supports multiple calendar integration with auto-sync functionality.</p>

        </div>
        {/* Image */}
        <div className="lg:w-1/2 flex justify-center">
          <img
            src={compliance}
            alt="AI Automation"
            className="rounded-lg shadow-lg"
          />
        </div>
      </div>
      <div className="flex flex-col gap-8 lg:flex-row justify-between items-center mb-12">
        {/* Content */}
        <div className="lg:w-1/2 mb-8 lg:mb-0">
        <h3 className="text-3xl font-bold  mb-2">				Service & Support:</h3>

        <p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed">
     <span className="font-bold ">	Service Desk:  </span>   Features a ticketing system, issue tracking, SLA management, and CAPA compliance for handling service requests. </p>
<p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed"><span className="font-bold ">		Booking Requests:  </span>Manages travel bookings (cabs, hotels, tickets) and workspace reservations.</p>

        </div>
        {/* Image */}
        <div className="lg:w-1/2 flex justify-center">
          <img
            src={compliance}
            alt="AI Automation"
            className="rounded-lg shadow-lg"
          />
        </div>
      </div>
      <div className="flex flex-col gap-8 lg:flex-row-reverse justify-between items-center mb-12">
        {/* Content */}
        <div className="lg:w-1/2 mb-8 lg:mb-0">
        <h3 className="text-3xl font-bold  mb-2">			Employee Engagement:</h3>

        <p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed">
     <span className="font-bold ">	Employee Portal: </span>  Provides a self-service portal for HR requests, personal information management, and more. </p>
<p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed"><span className="font-bold ">			Digital Business Card:   </span>Enables digital contact sharing and customizable business cards.</p>
<p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed"><span className="font-bold ">		Field Sense:   </span>Facilitates field data collection with mobile access for sales, business development, and operations teams.</p>

        </div>
        {/* Image */}
        <div className="lg:w-1/2 flex justify-center">
          <img
            src={compliance}
            alt="AI Automation"
            className="rounded-lg shadow-lg"
          />
        </div>
      </div>
      <div className="flex flex-col gap-8 lg:flex-row justify-between items-center mb-12">
        {/* Content */}
        <div className="lg:w-1/2 mb-8 lg:mb-0">
        <h3 className="text-3xl font-bold  mb-2">		Skill Grow:</h3>

        <p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed">
     <span className="font-bold ">	Skill Development: </span>  Offers training programs, certification tracking, and skill assessments to enhance employee capabilities. </p>
<p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed"><span className="font-bold ">		Recognition & Rewards:   </span>Includes reward programs, performance reviews, and recognition badges to boost employee motivation.</p>

        </div>
        {/* Image */}
        <div className="lg:w-1/2 flex justify-center">
          <img
            src={compliance}
            alt="AI Automation"
            className="rounded-lg shadow-lg"
          />
        </div>
      </div>
      <div className="flex flex-col gap-8 lg:flex-row-reverse justify-between items-center mb-12">
        {/* Content */}
        <div className="lg:w-1/2 mb-8 lg:mb-0">
        <h3 className="text-3xl font-bold  mb-2">			Meeting Management</h3>

        <p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed">
     <span className="font-bold ">	Meeting Tools:</span>   Supports agenda management, minutes of meeting (MOM) transcribing, and follow-up tracking for efficient meetings.  </p>
<p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed"><span className="font-bold ">	MOM Integration: </span>Automates MOM generation and distribution to ensure clear communication post-meetings.</p>
        </div>
        {/* Image */}
        <div className="lg:w-1/2 flex justify-center">
          <img
            src={compliance}
            alt="AI Automation"
            className="rounded-lg shadow-lg"
          />
        </div>
      </div>

      {/* Second Section */}
      <div className="flex flex-col gap-8 lg:flex-row justify-between items-center mb-12">
        {/* Content */}
        <div className="lg:w-1/2 mb-8 lg:mb-0">
        <h4 className="text-3xl font-bold   mb-2">		Reputation Management</h4>
    <p className="text-xl  mb-4 text-justify font-serif text-gray-800 leading-relaxed">
   <span className="font-bold ">Online Reputation:</span>	 Monitors social media, analyses brand sentiment, and manages online reviews to safeguard and enhance brand reputation.    </p>

        </div>
        {/* Image */}
        <div className="lg:w-1/2 flex justify-center">
          <img
            src={audit}
            alt="Team Taskforce"
            className="rounded-lg shadow-lg"
          />
        </div>
      </div>
    
      
      
    
    
    </div>
  );
};

export default KnowMorePage2;
