import { getItemInLocalStorage } from "./localStorage";
const today = new Date();
const year = today.getFullYear();
const month = String(today.getMonth() + 1).padStart(2, "0");
const day = String(today.getDate()).padStart(2, "0");
const formattedDate = `${year}-${month}-${day}`;
const siteID = getItemInLocalStorage("SITEID")
export const initialAddAssetFormData = {
    area: "",
    site_id: siteID,
    building_id: "",
    floor_id: "",
    unit_id: "",
    name: "",
    asset_number: "",
    serial_number: "",
    model_number: "",
    wing_id: "",
    purchase_cost: "",
    capacity: "",
    unit: "",
    group: "",
    sub_group: "",
    asset_type: "",
    purchased_on: formattedDate,
    breakdown: false,
    critical: false,
    installation: formattedDate,
    warranty: false,
    warranty_expiry: formattedDate,
    is_meter: false,
    meter_type: "",
    applicable_meter_category: "",
    parent_meter: "",
    meter_category: "",
    vendor_id: "",
  
    consumptionassetmeasure: "",
    unittype: "",
    min: "",
    max: "",
    belowvalue: "",
    abovevalue: "",
    multiplierfactor: "",
    checkpreviousreading: "",
    nonConsumptionAssetMeasure: "",
    nonunittype: "",
    nonmin: "",
    nonmax: "",
    nonbelowvalue: "",
    nonabovevalue: "",
    nonmultiplierfactor: "",
    noncheckprevreading: "",
    subname: "",
    subunittype: "",
    submin: "",
    submax: "",
    subbelowvalue: "",
    subabovevalue: "",
    subcheckprevreading: "",
  
    invoice: [],
    insurance: [],
    manuals: [],
    others: [],
  };